Repository taulazer/tau, pull requests merged in 2020-09, with the labels that each got.

#120 Fix Cinema mod not working as expected
  osu.Game.Rulesets.Tau/Mods/TauModCinema.cs
  osu.Game.Rulesets.Tau/TauRuleset.cs
Labels: bug

#121 Update osu and fix 0 scores
  osu.Game.Rulesets.Tau/Beatmaps/TauBeatmap.cs
  osu.Game.Rulesets.Tau/TauDifficultyCalculator.cs
  osu.Game.Rulesets.Tau/TauRuleset.cs
  osu.Game.Rulesets.Tau/osu.Game.Rulesets.Tau.csproj
Labels: bug, dependencies

#122 Fix combo-colouring
  osu.Game.Rulesets.Tau/TauRuleset.cs
Labels: bug

#127 Update osu
  osu.Game.Rulesets.Tau/Beatmaps/TauBeatmapConverter.cs
  osu.Game.Rulesets.Tau/osu.Game.Rulesets.Tau.csproj
Labels: dependencies
