Repository taulazer/tau, pull requests merged in 2020-03, with the labels that each got.

#10 Reduce amount of aliasing
  tau/osu.Game.Rulesets.tau/Objects/Drawables/DrawabletauHitObject.cs
  tau/osu.Game.Rulesets.tau/UI/Cursor/tauCursor.cs
  tau/osu.Game.Rulesets.tau/UI/tauPlayfield.cs
Labels: enhancement

#22 CodeFactor Inconsistencies
  tau/osu.Game.Rulesets.tau/Mods/TauModBlinds.cs
  tau/osu.Game.Rulesets.tau/UI/Cursor/tauCursor.cs
Labels: code quality

#28 Fix scaling issue
  osu.Game.Rulesets.tau/Objects/Drawables/DrawabletauHitObject.cs
  osu.Game.Rulesets.tau/UI/tauPlayfield.cs
Labels: needs tests

#30 Add Autoplay functionality
  osu.Game.Rulesets.tau/Replays/tauAutoGenerator.cs
  osu.Game.Rulesets.tau/Replays/tauFramedReplayInputHandler.cs
  osu.Game.Rulesets.tau/Replays/tauReplayFrame.cs
  osu.Game.Rulesets.tau/UI/TauPlayfieldAdjustmentContainer.cs
  osu.Game.Rulesets.tau/UI/tauDrawableRuleset.cs
  osu.Game.Rulesets.tau/UI/tauPlayfield.cs
Labels: enhancement

#36 Fix scaling issues
  osu.Game.Rulesets.tau/Replays/tauAutoGenerator.cs
  osu.Game.Rulesets.tau/UI/TauPlayfieldAdjustmentContainer.cs
  osu.Game.Rulesets.tau/UI/tauPlayfield.cs
Labels: needs tests
