Repository taulazer/tau, pull requests merged in 2020-07, with the labels that each got.

#107 Make TauHitObject abstract
  osu.Game.Rulesets.Tau/Beatmaps/TauBeatmapConverter.cs
  osu.Game.Rulesets.Tau/Mods/TauModRelax.cs
  osu.Game.Rulesets.Tau/Objects/Beat.cs
  osu.Game.Rulesets.Tau/Objects/Drawables/DrawableBeat.cs
  osu.Game.Rulesets.Tau/Objects/Drawables/DrawableTauHitObject.cs
  osu.Game.Rulesets.Tau/Objects/TauHitObject.cs
  osu.Game.Rulesets.Tau/UI/Cursor/TauCursor.cs
  osu.Game.Rulesets.Tau/UI/TauDrawableRuleset.cs
  osu.Game.Rulesets.Tau/UI/TauPlayfield.cs
Labels: code quality

#109 Implement Hard Beat
  osu.Game.Rulesets.Tau.Tests/Objects/TestSceneHardBeats.cs
  osu.Game.Rulesets.Tau.Tests/osu.Game.Rulesets.Tau.Tests.csproj
  osu.Game.Rulesets.Tau/Beatmaps/TauBeatmapConverter.cs
  osu.Game.Rulesets.Tau/Mods/TauModHardRock.cs
  osu.Game.Rulesets.Tau/Mods/TauModRelax.cs
  osu.Game.Rulesets.Tau/Objects/Drawables/DrawableBeat.cs
  osu.Game.Rulesets.Tau/Objects/Drawables/DrawableHardBeat.cs
  osu.Game.Rulesets.Tau/Objects/Drawables/DrawableTauJudgement.cs
  osu.Game.Rulesets.Tau/Objects/HardBeat.cs
  osu.Game.Rulesets.Tau/Replays/TauAutoGenerator.cs
  osu.Game.Rulesets.Tau/TauRuleset.cs
  osu.Game.Rulesets.Tau/UI/KiaiHitExplosion.cs
  osu.Game.Rulesets.Tau/UI/TauDrawableRuleset.cs
  osu.Game.Rulesets.Tau/UI/TauPlayfield.cs
  osu.Game.Rulesets.Tau/osu.Game.Rulesets.Tau.csproj
Labels: enhancement

#111 Cleanup
  osu.Game.Rulesets.Tau.Tests/Objects/TestSceneHardBeats.cs
  osu.Game.Rulesets.Tau.Tests/TestSceneOsuPlayer.cs
  osu.Game.Rulesets.Tau.Tests/VisualTestRunner.cs
  osu.Game.Rulesets.Tau/Beatmaps/TauBeatmapConverter.cs
  osu.Game.Rulesets.Tau/Extensions.cs
  osu.Game.Rulesets.Tau/Judgements/ComboResult.cs
  osu.Game.Rulesets.Tau/Mods/TauModBlinds.cs
  osu.Game.Rulesets.Tau/Mods/TauModFlashlight.cs
  osu.Game.Rulesets.Tau/Mods/TauModHardRock.cs
  osu.Game.Rulesets.Tau/Mods/TauModHidden.cs
  osu.Game.Rulesets.Tau/Mods/TauModRelax.cs
  osu.Game.Rulesets.Tau/Objects/Beat.cs
  osu.Game.Rulesets.Tau/Objects/Drawables/DrawableBeat.cs
  osu.Game.Rulesets.Tau/Objects/Drawables/DrawableHardBeat.cs
  osu.Game.Rulesets.Tau/Objects/Drawables/DrawableTauHitObject.cs
  osu.Game.Rulesets.Tau/Objects/Drawables/DrawableTauJudgement.cs
  osu.Game.Rulesets.Tau/Objects/HardBeat.cs
  osu.Game.Rulesets.Tau/Objects/TauHitObject.cs
  osu.Game.Rulesets.Tau/Replays/TauAutoGenerator.cs
  osu.Game.Rulesets.Tau/Replays/TauReplayFrame.cs
  osu.Game.Rulesets.Tau/TauRuleset.cs
  osu.Game.Rulesets.Tau/UI/Components/PlayfieldVisualization.cs
  osu.Game.Rulesets.Tau/UI/Cursor/TauCursor.cs
  osu.Game.Rulesets.Tau/UI/KiaiHitExplosion.cs
  osu.Game.Rulesets.Tau/UI/TauPlayfield.cs
  osu.Game.Rulesets.Tau/UI/TauPlayfieldAdjustmentContainer.cs
  osu.Game.Rulesets.Tau/UI/TauReplayRecorder.cs
Labels: code quality

#114 Fix relax mod interfering with replays
  osu.Game.Rulesets.Tau/Mods/TauModRelax.cs
Labels: bug

#113 Editor
  osu.Game.Rulesets.Tau.Tests/TestSceneTauEditor.cs
  osu.Game.Rulesets.Tau/Beatmaps/TauBeatmapConverter.cs
  osu.Game.Rulesets.Tau/Edit/BeatCompositionTool.cs
  osu.Game.Rulesets.Tau/Edit/Blueprints/BeatPlacementBlueprint.cs
  osu.Game.Rulesets.Tau/Edit/Blueprints/BeatSelectionBlueprint.cs
  osu.Game.Rulesets.Tau/Edit/Blueprints/HardBeatPlacementBlueprint.cs
  osu.Game.Rulesets.Tau/Edit/Blueprints/HardBeatSelectionBlueprint.cs
  osu.Game.Rulesets.Tau/Edit/Blueprints/HitPiece.cs
  osu.Game.Rulesets.Tau/Edit/Blueprints/TauSelectionBlueprint.cs
  osu.Game.Rulesets.Tau/Edit/HardBeatCompositionTool.cs
  osu.Game.Rulesets.Tau/Edit/TauBlueprintContainer.cs
  osu.Game.Rulesets.Tau/Edit/TauHitObjectComposer.cs
  osu.Game.Rulesets.Tau/Edit/TauSelectionHandler.cs
  osu.Game.Rulesets.Tau/Extensions.cs
  osu.Game.Rulesets.Tau/Objects/Drawables/DrawableBeat.cs
  osu.Game.Rulesets.Tau/Objects/Drawables/DrawableHardBeat.cs
  osu.Game.Rulesets.Tau/Objects/TauHitObject.cs
  osu.Game.Rulesets.Tau/TauRuleset.cs
  osu.Game.Rulesets.Tau/UI/Cursor/TauCursor.cs
  osu.Game.Rulesets.Tau/UI/KiaiHitExplosion.cs
  osu.Game.Rulesets.Tau/UI/TauPlayfield.cs
Labels: enhancement
