Repository taulazer/tau, pull requests merged in 2021-11, with the labels that each got.

#229 Implement skinnable cursor
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-beat.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-cursor.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-field-background.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-field-overlay.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-handle-line.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-handle.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-hard-beat.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-kiai-0.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-kiai-1.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-kiai-2.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-kiai-3.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-kiai-4.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-kiai-5.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-kiai-big-0.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-kiai-big-1.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-kiai-big-2.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-kiai-big-3.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-kiai-big-4.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-kiai-big-5.png
  osu.Game.Rulesets.Tau.Tests/Resources/metrics-skin/tau-paddle.png
  osu.Game.Rulesets.Tau.Tests/Resources/special-skin/tau-beat.png
  osu.Game.Rulesets.Tau.Tests/Resources/special-skin/tau-cursor.png
  osu.Game.Rulesets.Tau.Tests/Resources/special-skin/tau-field-background.png
  osu.Game.Rulesets.Tau.Tests/Resources/special-skin/tau-field-overlay.png
  osu.Game.Rulesets.Tau.Tests/Resources/special-skin/tau-handle-line.png
  osu.Game.Rulesets.Tau.Tests/Resources/special-skin/tau-handle.png
  osu.Game.Rulesets.Tau.Tests/Resources/special-skin/tau-hard-beat.png
  osu.Game.Rulesets.Tau.Tests/Resources/special-skin/tau-kiai-big.png
  osu.Game.Rulesets.Tau.Tests/Resources/special-skin/tau-kiai.png
  osu.Game.Rulesets.Tau.Tests/Resources/special-skin/tau-paddle.png
  osu.Game.Rulesets.Tau/Resources/UI/ruleset-select-tau.wav
  osu.Game.Rulesets.Tau/Skinning/Default/CursorPiece.cs
  osu.Game.Rulesets.Tau/Skinning/Legacy/LegacyBeat.cs
  osu.Game.Rulesets.Tau/Skinning/Legacy/LegacyCursor.cs
  osu.Game.Rulesets.Tau/Skinning/Legacy/LegacyHandle.cs
  osu.Game.Rulesets.Tau/Skinning/Legacy/LegacyHardBeat.cs
  osu.Game.Rulesets.Tau/Skinning/Legacy/LegacyPlayfield.cs
  osu.Game.Rulesets.Tau/Skinning/Legacy/TauLegacySkinTransformer.cs
  osu.Game.Rulesets.Tau/TauSkinComponents.cs
  osu.Game.Rulesets.Tau/UI/Cursor/AbsoluteCursor.cs
  osu.Game.Rulesets.Tau/UI/KiaiHitExplosion.cs
Labels: enhancement

#234 Increase slider division count
  osu.Game.Rulesets.Tau/Beatmaps/TauBeatmapConverter.cs
  osu.Game.Rulesets.Tau/Mods/TauModLite.cs
Labels: enhancement

#239 Impliment Perfect mod and some code import sanity checks..
  osu.Game.Rulesets.Tau/Edit/Blueprints/TauSelectionBlueprint.cs
  osu.Game.Rulesets.Tau/Edit/TauBlueprintContainer.cs
  osu.Game.Rulesets.Tau/Edit/TauSelectionHandler.cs
  osu.Game.Rulesets.Tau/Mods/TauModLite.cs
  osu.Game.Rulesets.Tau/Mods/TauModPerfect.cs
  osu.Game.Rulesets.Tau/Replays/TauFramedReplayInputHandler.cs
  osu.Game.Rulesets.Tau/TauRuleset.cs
Labels: enhancement, code quality

#240 Fix Legacy Skin components not rendering on playfield.
  osu.Game.Rulesets.Tau/Skinning/Legacy/TauLegacySkinTransformer.cs
Labels: bug
